spring.application.name=school
spring.datasource.url= jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username= student
spring.datasource.password= chocolatefrog

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= validate
spring.jpa.show-sql=true

path.to.avatars.folder= /avatars

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

server.port=8081
constant.text=Was invoked method for {} serverPort {}, activeProfile {}
logging.level.ru.hogwarts.school.service.AvatarService=DEBUG
logging.level.ru.hogwarts.school.service.FacultyService=DEBUG
logging.level.ru.hogwarts.school.service.StudentService=DEBUG
